# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: "24"
        
    - name: verify Node.js
      run: |
        node --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-playwright playwright pytest-xdist pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Playwright Chromium
      run: |
        playwright install --with-deps chromium

    - name: Run Tests
      run: |
       pytest tests

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
       name: pytest-html-report
       path: report.html

    - name: Send Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
       server_address: smtp.gmail.com
       server_port: 465
       secure: true
       username: ${{secrets.USERNAME}}
       password: ${{secrets.EMAIL_PASSWORD}}
       subject: "Playwright Test Results - ${{job.status}}"
       to: prasanth.vishnubhatla@gmail.com
       from:
       body: |
         Hi Team, 

         Playwright execution is Complete. 
         Status: ${{job.status}}

         Report:
         https://github.com/${{github.repository}}/actions/run/${{github.run_id}}

         Open the workflow and download the pytest-html-report artifact.
      
